version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  groups:
    ESLint:
      patterns: ["*eslint*"]
  open-pull-requests-limit: 10
  reviewers:
  - camel-tooling/vs-code-dependabot-reviewers
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - camel-tooling/vs-code-dependabot-reviewers
