apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: example-pipe
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: timer-source
    properties:
      message: "hello world"
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink
    #properties:
      #key: "value"
