name: Test matrixes of VS Code versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        vscode-version: ["1.61.2", "1.66.2"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install global dependencies
      run: npm install -g typescript vsce
    - name: npm-ci
      run: npm ci
    - name: npm-compile
      run: npm run compile
    - name: test
      run: xvfb-run -a npm test
      env:
          CODE_VERSION: ${{ matrix.vscode-version }}
    - name: ui-test
      env:
          CODE_VERSION: ${{ matrix.vscode-version }}
      run: xvfb-run -a npm run ui-test
    - name: Store VS Code logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: vscode-logs ${{ matrix.vscode-version }}
        path: ~/.config/Code/logs
    - name: Store VS Code UI Tests screenshots on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ui-test-screenshots ${{ matrix.vscode-version }}
        path: test-resources/screenshots
