name: Test matrixes of VS Code versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        vscode-version: ["1.57.0", "1.60.0"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
    - name: Install global dependencies
      run: npm install -g typescript vsce
    - name: npm-ci
      run: npm ci
    - name: npm-compile
      run: npm run compile
    - name: test
      run: xvfb-run -a npm test
      env:
          CODE_VERSION: ${{ matrix.vscode-version }}
    - name: ui-test
      env:
          CODE_VERSION: ${{ matrix.vscode-version }}
      run: xvfb-run -a npm run ui-test
