# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install global dependencies
      run: npm install -g typescript vsce
    - name: npm-ci
      run: npm ci
    - name: npm-compile
      run: npm run compile
    - name: test
      run: npm test
    - name: ui-test
      run: npm run ui-test
    - name: Store VS Code logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: vscode-logs
        path: ~/.config/Code/logs
    - name: Store VS Code UI Tests screenshots on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ui-test-screenshots
        path: test-resources/screenshots
